---
-   name: download sh file
    ansible.builtin.get_url:
        url: "{{ link }}"
        dest: /root/cmakeInstaller.sh
        mode: '0700'

-   name: run installer
    ansible.builtin.shell:
        cmd: "sh cmakeInstaller.sh --skip-license --prefix={{ path }}"
        chdir: /root
