---
#-   name: download legacy driver (470)
#    ansible.builtin.get_url:
#        url: https://us.download.nvidia.com/tesla/460.106.00/NVIDIA-Linux-x86_64-460.106.00.run
#        dest: /root/NVIDIA-Linux-x86_64-460.106.00.run

-   name: download run file
    ansible.builtin.get_url:
        url: https://us.download.nvidia.com/tesla/535.161.08/NVIDIA-Linux-x86_64-535.161.08.run
        dest: /root/

-   name: install gcc and kernel-devel
    ansible.builtin.dnf:
        name:
        -   gcc
        -   kernel-devel
        state: present

-   name: exec run file
    ansible.builtin.shell: sh NVIDIA-Linux-x86_64-535.161.08.run -s
