---
#-   name: download legacy dirver (470)
#    ansible.builtin.get_url:
#        url: https://us.download.nvidia.com/tesla/460.106.00/NVIDIA-Linux-x86_64-460.106.00.run
#        dest: /root/NVIDIA-Linux-x86_64-460.106.00.run

-   name: download run file
    ansible.builtin.get_url:
        url: https://us.download.nvidia.com/XFree86/Linux-x86_64/470.199.02/NVIDIA-Linux-x86_64-470.199.02.run
        dest: /root/

-   name: exec run file
    ansible.builtin.shell: sh NVIDIA-Linux-x86_64-470.199.02.run -s
