---
-   name: download runfile
    ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda_12.2.0_535.54.03_linux.run
        dest: /root/cuda_12.2.0_535.54.03_linux.run
        mode: '0700'

-   name: install cuda
    ansible.builtin.shell: /root/cuda_12.2.0_535.54.03_linux.run --silent --toolkit --toolkitpath=/srv/exports/software/cuda-12.2 --samples --samplespath=/srv/exports/software/cuda-12.2/samples
