---
-   name: setup module system
    hosts: all

    roles:
      -   role: install-lmod

#-   name: install gcc-12.2.0 in exports
#    hosts: head
#
#    roles:
#      -   role: install-gcc
#          vars:
#              ver: "12.2.0"

-   name: config lmod on head on nfs
    hosts: head
    roles:
      -   role: configure-lmod

-   name: set user env vars for lmod
    hosts: all
    roles:
      -   role: configure-lmod-user-env
