---
-   name: setup compute node
    hosts: com

    roles:
    #-   role: fix-dnf
    -   role: update
    -   role: configure-sshd
    -   role: mount-nfs
        vars:
            serverPath: "/srv/exports/home"
            clientPath: "/home/users"
    -   role: create-users
        vars:
            homePath: "/home/users"
    -   role: selinux
        vars:
            plice: "use_nfs_home_dirs"
    -   role: mount-nfs
        vars:
            serverPath: "srv/exports/software"
            clientPath: "/software"
