---
-   name: setup Head
    hosts: head

    roles:
    -   role: linkHome
        vars:
            src: "/srv/exports/home"
            dest: "/home/head"
    -   role: folder
        vars:
            path: "/srv/exports/software"
    -   role: share-nfs
        vars:
            path: "/srv/exports/software"
