---
-   name: update
    hosts: all

    roles:
    -   role: update

-   name: create users for slurm and munge
    hosts: all

    roles:
    -   role: create-slurm-users

-   name: enable firewall for slurm
    hosts: all

    roles:
    -   role: enable-firewall-ports
        vars:
        -   ports:
            -   7012
            -   7013

-   name: install slurm and dependend munge on head node
    hosts: head

    roles:
    -   role: install-munge
    -   role: install-slurm
        vars:
            path: "/root/slurm"
    -   role: enable-autostart
        vars:
            services:
            -   slurmctld
            -   slurmd
    -   role: munge-create-key
    -   role: enable-autostart
        vars:
            services:
            -   munge.service

-   name: install slurm and dependend munge on com node (slurm.rpm form head)
    hosts: com

    roles:
    -   role: install-munge
    -   role: install-slurm-from-head
    -   role: munge-key-roleout
    -   role: enable-autostart
        vars:
            services:
            -   slurmd
            -   munge.service

-   name: roleout slurm.conf
    hosts: all

    roles:
    -   role: configure-slurm


