---
-   name: setup Head
    hosts: head

    roles:
    -   role: share-nfs
        vars:
            path: "/srv/exports/home"
            client: "localhost"

    -   role: mount-nfs
        vars:
            serverPath: "/srv/exports/home"
            clientPath: "/home/users"
            server: "localhost"

    -   role: folder
        vars:
            path: "/srv/exports/software"

    -   role: share-nfs
        vars:
            path: "/srv/exports/software"
            client: "localhost"

    -   role: share-nfs
        vars:
            path: "/srv/exports/software"
            client: "pc-t2-n1"

    -   role: share-nfs
        vars:
            path: "/srv/exports/home"
            client: "pc-t2-n1"

    -   role: mount-nfs
        vars:
            serverPath: "srv/exports/software"
            clientPath: "/software"
            server: "localhost"

    -   role: selinux
        vars:
            plice: "use_nfs_home_dirs"
