---
-   name: Install nfs-utils
    ansible.builtin.dnf:
        name: nfs-utils
        state: present
-   name: Mount nfs
    ansible.posix.mount:
        src: "{{server}}:{{serverPath}}"
        path: "{{clientPath}}"
        opts: rw,sync
        state: mounted
        fstype: nfs
