---
-   name: install
    ansible.builtin.dnf:
        name: mariadb

-   name: create folder
    ansible.builtin.file:
        path: "/root/rpmbuild/RPMS/x86_64"
        state: directory

-   name: get slurm rpms from head
    ansible.posix.synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
    delegate_to: "{{ head }}"
    with_fileglob: "/root/rpmbuild/RPMS/x86_64/*.rpm"

-   name: gather package_facts
    ansible.builtin.package_facts:
        manager: rpm

-   name: rpm install files
    ansible.builtin.command: "rpm --install /root/rpmbuild/RPMS/x86_64/{{ item }}-23.11.5-1.el9.x86_64.rpm" #installation will be in home of buiding user
    when: "item | string not in ansible_facts.packages"
    with_items:
    -   slurm
    #-   slurm-slurmctld
    -   slurm-slurmd
    -   slurm-perlapi
    -   slurm-pam_slurm
    -   slurm-libpmi
    -   slurm-torque
    -   slurm-devel
    -   slurm-contribs
    -   slurm-example-configs
    -   slurm-openlava

-   name: rpm reinstall files
    ansible.builtin.command: "rpm --reinstall /root/rpmbuild/RPMS/x86_64/{{ item }}-23.11.5-1.el9.x86_64.rpm"
    when:
    -   "item | string in ansible_facts.packages"
    -   reinstall
    with_items:
        -   slurm
        #-   slurm-slurmctld
        -   slurm-slurmd
        -   slurm-perlapi
        -   slurm-pam_slurm
        -   slurm-libpmi
        -   slurm-torque
        -   slurm-devel
        -   slurm-contribs
        -   slurm-example-configs
        -   slurm-openlava
