---
-   name: set var openMPI version name
    ansible.builtin.set_fact:
        openMPIVersionName: "openmpi-{{ openMPIVersion }}"

-   name: set openmpi path for template
    ansible.builtin.set_fact:
        openMPIAbsolutePath: "{{ (sharedSoftwarePath, 'openmpi', openMPIVersionName) | path_join }}"

-   name: set var for openMPI modulefile name
    ansible.builtin.set_fact:
        openMPIModulefileName: "{{ openMPIVersionName }}.lua"

-   name: put openmpi modulefile to modulefile location
    ansible.builtin.template:
        src: openmpi-version.lua.j2
        dest: "{{ (modulefilesFolder, 'openmpi', openMPIModulefileName) | path_join }}"
        force: false # do not override existing file
