---
-   name: Install nfs-utils
    ansible.builtin.dnf:
        name: nfs-utils
        state: present

-   name: Unmount dead nfs
    ansible.builtin.shell: "umount -f -l {{ clientPath }}"
    register: result
    failed_when:
    -   result.rc != 0
    -   '"not mounted" not in result.stderr'

-   name: Unmount nfs
    ansible.posix.mount:
        path: "{{clientPath}}"
        state: unmounted

