---
-   name: create folder for download
    ansible.builtin.file:
        path: "{{ (installerTmpFolder, 'openmpi') | path_join }}"
        state: directory

-   name: download openMPI and unpack
    ansible.builtin.unarchive:
        src: https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.6.tar.bz2
        dest: "{{ (installerTmpFolder, 'openmpi') | path_join }}"
        remote_src: yes

-   name: configure openmpi
    ansible.builtin.command:
        cmd: ./configure --prefix=/apps/openmpi/openmpi-4.1.6 --with-slurm --with-pmi --with-pmix --with-cuda --with-singularity --with-ucx=/apps/ucx --without-verbs --enable-orterun-prefix-by-default
        chdir: "{{ (installerTmpFolder, 'openmpi', 'openmpi-4.1.6') | path_join }}"
        creates: "{{ (installerTmpFolder, 'openmpi', 'openmpi-4.1.6', 'Makefile') | path_join }}"

-   name: make
    community.general.make:
        chdir: "{{ (installerTmpFolder, 'openmpi', 'openmpi-4.1.6') | path_join }}"

-   name: make install
    community.general.make:
        chdir: "{{ (installerTmpFolder, 'openmpi', 'openmpi-4.1.6') | path_join }}"
        target: install

#--with-slurm --with-pmi=/usr/include/slurm --with-pmi-libdir=/usr
