---
-   name: create folder for download
    ansible.builtin.file:
        path: "{{ (installer-tmp-folder, 'openmpi') | path_join }}"
        state: directory

-   name: download openMPI and unpack
    ansible.builtin.unarchive:
        src: https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5.tar.bz2
        dest: "{{ (installer-tmp-folder, 'openmpi') | path_join }}"
        remote_src: yes

-   name: configure openmpi
    ansible.builtin.command:
        #cmd: ./configure --prefix=/srv/exports/software/openmpi/openmpi-4.1.5
        # we had to install to the exported nsf directory, since otherwise in some cases openmpi tried to follow the
        # install path in exports, which doesnt exist on the compute node
        cmd: ./configure --prefix=/apps/openmpi/openmpi-4.1.5 --with-slurm --with-pmi --with-pmix --with-cuda --with-singularity --with-ucx=/apps/ucx --without-verbs --enable-orterun-prefix-by-default
        chdir: "{{ (installer-tmp-folder, 'openmpi', 'openmpi-4.1.5') | path_join }}"
        creates: "{{ (installer-tmp-folder, 'openmpi', 'openmpi-4.1.5', 'Makefile') | path_join }}"

-   name: make
    community.general.make:
        chdir: "{{ (installer-tmp-folder, 'openmpi', 'openmpi-4.1.5') | path_join }}"

-   name: make install
    community.general.make:
        chdir: "{{ (installer-tmp-folder, 'openmpi', 'openmpi-4.1.5') | path_join }}"
        target: install

#--with-slurm --with-pmi=/usr/include/slurm --with-pmi-libdir=/usr
