---
-   name: download dependentces for pmix
    ansible.builtin.dnf:
        name:
        -   m4
        -   autoconf
        -   automake
        -   libtool
        -   flex
        -   libevent
        -   git
        -   hwloc
        -   hwloc-devel
        state: present

-   name: download the git repo
    ansible.builtin.git:
        repo: 'https://github.com/pmix/pmix'
        dest: "{{ (installer-tmp-folder, 'pmix') | path_join }}"

-   name: autogen
    ansible.builtin.shell: ./autogen.pl
    args:
        chdir: "{{ (installer-tmp-folder, 'pmix') | path_join }}"
        creates: "{{ (installer-tmp-folder, 'pmix', 'configure') | path_join }}"

-   name: create build dir
    ansible.builtin.file:
        path: "{{ (installer-tmp-folder, 'pmix', 'build') | path_join }}"
        state: directory

-   name: configure
    ansible.builtin.shell:
        cmd: "../configure --prefix={{ path }}"
        chdir: "{{ (installer-tmp-folder, 'pmix', 'build') | path_join }}"
        creates: "{{ (installer-tmp-folder, 'pmix', 'build', 'Makefile') | path_join }}"

-   name: build pmix
    community.general.make:
        chdir: "{{ (installer-tmp-folder, 'pmix', 'build') | path_join }}"
        target: all

-   name: install pmix
    community.general.make:
        chdir: "{{ (installer-tmp-folder, 'pmix', 'build') | path_join }}"
        target: install
