---
-   name: Iterate over StudOn IDs and create with onetime password
    ansible.builtin.user:
        name: "{{ item.name }}"
        home: "{{ homePath }}/{{ item.name }}"
        create_home: true
        password: "{{ item.name | password_hash('sha512') }}"
        update_password: on_create
    register: "changed"
    loop: "{{ cluster-users }}"

-   name: let user password expire now
    ansible.builtin.command:
        cmd: "passwd --expire {{ item.name }}"
    when: " item.changed is true"
    loop: "{{ changed.results }}"
