---
-   name: set name for cuda modulefile
    ansible.builtin.set_fact:
        cudaVersionName: "cuda-{{ cuda_version }}"

-   name: set link if nesasary information is found
    ansible.builtin.set_fact:
        link: "https://developer.download.nvidia.com/compute/cuda/{{ cuda_version }}/local_installers/cuda_{{ cuda_version }}_{{ cudaDriverVersion}}_linux.run"
    when: cudaDriverVersion is definded

-   name: download runfile
    ansible.builtin.get_url:
        url: "{{ link }}"
        dest: "{{ (installerTmpFolder, 'cudaInstaller.run' ) | path_join }}"
        mode: '0700'

-   name: install gcc
    ansible.builtin.dnf:
        name: gcc
        state: present

-   name: install cuda
    ansible.builtin.shell:
        cmd: "{{ (installerTmpFolder, 'cudaInstaller.run' ) | path_join }} --silent --toolkit --toolkitpath={{ (sharedSoftwarePath, 'cuda', cudaVersionName) | path_join }} --samples --samplespath={{ (sharedSoftwarePath, 'cuda' cudaVersionName, 'samples' ) | path_join }}"
