---
-   name: download runfile
    ansible.builtin.get_url:
        url: "{{ link }}"
        dest: /root/cudaInstaller.run
        mode: '0700'

-   name: install gcc
    ansible.builtin.dnf:
        name: gcc
        state: present

-   name: install cuda
    ansible.builtin.shell:
        cmd: "/root/cudaInstaller.run --silent --toolkit --toolkitpath={{ install_path }} --samples --samplespath={{ (install_path, '/samples' ) | path_join }}"
