---
-   name: add docker repo
    ansible.builtin.command:
        cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

-   name: install docker
    ansible.builtin.dnf:
        name:
        -   docker-ce 
        -   docker-ce-cli
        -   containerd.io
        state: present
    