-   name: Mount nfs form head to com
    hosts: com

    tasks:
    -   name: Install nfs-utils
        ansible.builtin.dnf:
            name: nfs-utils
            state: present
    -   name: Mount nfs
        ansible.posix.mount:
            src: pc-t2-n0:/srv/exports/home
            path: /home
            opts: rw,sync
            state: mounted
            fstype: nfs
    -   name: SELinux allow nfs homes
        ansible.posix.seboolean:
            name: use_nfs_home_dirs
            state: true
            persistent: true

