-   name: Update
    hosts: all

    tasks:
    -   name: Update packte manager
        ansible.builtin.dnf:
            name: "*"
            state: latest
    -   meta: end_play
        when:
                "'pip' in ansible_facts.packages"
    -   name: Install tool to update pip python packte manager
        ansible.builtin.pip:
            name: pip-review
    -   name: Update pip python packte manager
        ansible.builtin.command: pip-review --local --auto
