---
-   name: get slurm rpms from head
    ansible.posix.synchronize:
        src: "/root/rpmbuild/RPMS/x86_64"
        dest: "{{ item }}"
    delegate_to: pc-t2-n0
    with_fileglob: "/root/rpmbuild/RPMS/x86_64/*.rpm"

-   name: gather package_facts
    ansible.builtin.package_facts:
        manager: rpm

-   name: rpm install files
    ansible.builtin.command: "rpm --install /root/rpmbuild/RPMS/x86_64/{{ item }}-23.02.2-1.el9.x86_64.rpm" #installtion will be in home of buiding user
    when: "'{{ item }}' not in ansible_facts.packages"
    with_items:
    -   slurm
    -   slurm-slurmctld
    -   slurm-slurmd
    -   slurm-perlapi
    -   slurm-pam_slurm
    -   slurm-libpmi
    -   slurm-torque
    -   slurm-devel
    -   slurm-contribs
    -   slurm-example-configs
    -   slurm-openlava
