---
-   name: add zone
    ansible.posix.firewalld:
        zone: "{{ zone }}"
        state: persent

-   name: add nodes to zone
    ansible.posix.firewalld:
        source: "{{ item }}"
        zone: "{{ zone }}"
        state: enabled
    loop: "{{ nodes }}"

-   name: enable ports
    ansible.posix.firewalld:
        zone: "{{ zone }}"
        port: "{{ item }}/{{ protocol }}"
        state: enabled
        permanent: true
    loop: "{{ ports }}"
    when: ports is defined

-   name: enable port
    ansible.posix.firewalld:
        zone: "{{ zone }}"
        port: "{{ port }}/{{ protocol }}"
        state: enable
        permanent: true
    when: port is defined

-   name: enable service
    ansible.posix.firewalld:
        zone: "{{ zone }}"
        service: "{{ service }}"
        state: enable
        permanent: true
    when: service is defined

-   name: reload firewalld
    ansible.builtin.command:
        cmd: "firewall-cmd --reload"
