---
-   name: Update packte manager
    ansible.builtin.dnf:
        name: "*"
        state: latest

-   name: gather the package facts
    ansible.builtin.package_facts:
        manager: auto

-   name: Install tool update and perform update of pip
    block:
    -   name: Install tool to update pip python packte manager
        ansible.builtin.pip:
            name: pip-review

    -   name: Update pip python packte manager
        ansible.builtin.command: pip-review --local --auto
    when: "'pip' in ansible_facts.packages"
