---
-   name: set prompt color
    ansible.builtin.lineinfile:
        path: "{{ (homePath, item.name, '.bashrc' ) | path_join }}"
        line: "export PS1=\"{{ colorScheme }}\""
    loop: "{{ cluster-users }}"
